version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: custom-fhir-repo
    hostname: custom-fhir-repo
#   command: --check-caps false
    ports: 
      - 2001:1972
      - 2002:52773
      - 2003:53773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
